### ISSUE TITLE
Declare your conflicts of interest

### ISSUE THREAD

**Issue by impredicative** [bitcoin-0/btc0#4]
Which banks do you or your sponsors work for? This declaration must be thorough.

**Comment by carnage** [comment]
I do not work for a bank, I have never worked for a bank and due to the risk adverse reaction banks have taken to the UK's IR35 changes this year, will very likely never work for a bank.

At the moment, this project has no sponsors and doesn't really need any, the small eventual costs for things like web hosting will be covered, personally, by me or other volunteers, though I'm probably just going to use github.io for the time being. 

As for other conflicts of interest: I currently live on this planet and would like it to remain habitable.
